# Generated by Django 5.2.7 on 2025-11-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='specialist_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
