# Generated by Django 5.2.7 on 2025-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfig_in_person_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ACH_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ACH_routing_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
