# Generated by Django 5.2.7 on 2025-10-20 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_ach_bank_name_user_ach_routing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, help_text='State or City of salesman for in-person appointments', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_finalized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
